### ISSUE TITLE
Mouse not working when using custom settings

### ISSUE THREAD

**Issue by Aqualy** [davidkgriggs/DKG-Theme-Modifier#1]
I'm not able to click anything with my mouse or use it to select games/options, but only when changing the default DKG settings. I'm only able to use a controller.

**Comment by davidkgriggs** [comment]
Do you mean when in fullscreen mode you cannot use the mouse? What theme? And what options do you have turned on? If you have Video Intro turned on but have not set up a video correctly then the mouse will not work.
