### ISSUE TITLE
Aspect ratio is not being respected and settings not applying

### ISSUE THREAD

**Issue by Deezusol** [davidkgriggs/DKG-Theme-Modifier#2]
Anytime I attempt to apply settings for PS5ish  it says that the settings have been applied. However, there are two issues.

1. Apply Defaults does not work, no settings actually change.
2. Regardless of what I set in Grid View my covers are being displayed as full covers, not squares like I want.

I have tried uninstalling and reinstalling, disabling and reenabling the add-on, and have waited for the last two releases to fix these issues but so far nothing.

Any clue as to what it might be?

And thank you for all the work on this project and PS5ish.

**Comment by davidkgriggs** [comment]
When you Restore Defaults the settings in the window will not change, in the background however it downloads default files and overwrites them in the theme to set everything back to default. If you Restore Defaults and then you clicked Apply Changes you would be restoring all the defaults and then overwriting them with your changes. You just need to Restore Defaults and then save the window.

The Row of Games was changed to display any cover size. The idea is that people would download the covers they wanted in the aspect ratio they wanted. You have different cover sizes and you want to squash them all to be squares? I would need to do some work on the Row of Games for that to be achieved.

**Comment by Deezusol** [comment]
Thank you for the clarification. It seems my issue is with PS5ish then, should I open an issue/request there?

I assume the Row of Games change was in 4.2.0 of PS5ish, correct? And I understand the idea, but isn't swapping artwork for potentially hundreds of games more tedious than cropping them how it worked prior to v. 4.2.0? It discourages using any non-square based theme in Playnite.

I don't know how realistic of a suggestion this is, or how many others besides me may want the functionality of the older version, but perhaps a setting in the theme modifier to ignore the new Row of Games cropping would be possible at some point?
