### ISSUE TITLE
Add Modern UI Modded to DKG Theme Modifier

### ISSUE THREAD

**Issue by 0-Hex** [davidkgriggs/DKG-Theme-Modifier#5]
Per your DM on Discord, I've generated a update to Modern UI Modded with a unique theme ID so you can add it when you have time.

Also since your working on 1.5.0 of Modern UI, it would be best to leave Modern UI Modded settings in DKG Theme Modifier at 1.4.1 when you release that update, as while I saw your video on it and have some ideas about how I might change details view in modded the changes wont be made till sometime after you've released that update.

ID= PlayniteModernUIModded
Release Link= https://github.com/HexSupernatural/PlayniteModernUIModded/releases/tag/v3.5.0

**Comment by davidkgriggs** [comment]
Added support in v2.8.0 that's just released. You will need the same constants as the current Modern UI so that resetting to defaults etc works correctly. Grab a copy of the contstants from the Modern UI v1.5.0 which has just released.
